GET http://localhost:8080/users/list
Content-Type: application/x-www-form-urlencoded

###

GET http://localhost:8080/api/hello
Content-Type: application/x-www-form-urlencoded

###

GET http://localhost:8080/api/getUsers
Content-Type: application/x-www-form-urlencoded

###
POST http://localhost:8080/api/addClient
Content-Type: application/x-www-form-urlencoded

name = antonio

###

POST http://localhost:8080/api/addManager
Content-Type: application/x-www-form-urlencoded

name = toze

###
POST http://localhost:8080/api/addOwner
Content-Type: application/x-www-form-urlencoded

name = joao

###

POST http://localhost:8080/api/hello
Content-Type: application/x-www-form-urlencoded

name = joao

###

POST http://localhost:8080/api/hello
Content-Type: application/x-www-form-urlencoded

name = maria

###

POST http://localhost:8080/api/hello
Content-Type: application/x-www-form-urlencoded

name = jose

###


