GET http://localhost:8080/users/list
Content-Type: application/x-www-form-urlencoded

###

GET http://localhost:8080/api/hello
Content-Type: application/x-www-form-urlencoded

###

GET http://localhost:8080/api/getUsers
Content-Type: application/x-www-form-urlencoded

###

GET http://localhost:8080/properties/property/1
Content-Type: application/json

###
POST http://localhost:8080/users/addUser
Content-Type: application/json

{
"id": 5,
"role": "CLIENT",
"username": "newUser",
"password": "newPassword"
}

###
POST http://localhost:8080/users/login
Content-Type: application/json

{
"username": "newUser",
"password": "newPassword"
}

###
POST http://localhost:8080/properties/addProperty
Content-Type: application/json

{
  "id": 2,
  "name": "Casa ali",
  "location": "Almada",
  "owner": "newUser3"
}

###

POST http://localhost:8080/api/addManager
Content-Type: application/x-www-form-urlencoded

name = toze

###
POST http://localhost:8080/api/addOwner
Content-Type: application/x-www-form-urlencoded

name = joao

###

POST http://localhost:8080/api/hello
Content-Type: application/x-www-form-urlencoded

name = joao

###

POST http://localhost:8080/api/hello
Content-Type: application/x-www-form-urlencoded

name = maria

###

POST http://localhost:8080/api/hello
Content-Type: application/x-www-form-urlencoded

name = jose

###


